// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace back_end.Migrations
{
    [DbContext(typeof(WaterPathDbContext))]
    partial class WaterPathDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Domain.User.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", "waterPath");
                });

            modelBuilder.Entity("QualidadeCianoBacterias", b =>
                {
                    b.Property<int>("QualidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("CianoBacteriaId")
                        .HasColumnType("integer");

                    b.HasKey("QualidadeId", "CianoBacteriaId");

                    b.HasIndex("CianoBacteriaId");

                    b.ToTable("QualidadeCianoBacterias", "waterPath");
                });

            modelBuilder.Entity("QualidadeMetaisPesados", b =>
                {
                    b.Property<int>("QualidadeId")
                        .HasColumnType("integer");

                    b.Property<int>("MetalPesadoId")
                        .HasColumnType("integer");

                    b.HasKey("QualidadeId", "MetalPesadoId");

                    b.HasIndex("MetalPesadoId");

                    b.ToTable("QualidadeMetaisPesados", "waterPath");
                });

            modelBuilder.Entity("UsuarioCorpoHidrico", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.Property<int>("CorpoHidricoId")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioId", "CorpoHidricoId");

                    b.HasIndex("CorpoHidricoId");

                    b.ToTable("UsuarioCorpoHidricos", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.CianoBacteria.CianoBacteriaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColetaId")
                        .HasColumnType("integer");

                    b.Property<float>("Concentracao")
                        .HasColumnType("real");

                    b.Property<int?>("QualidadeFuturaEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.HasIndex("QualidadeFuturaEntityId");

                    b.ToTable("CianoBacterias", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.Codigo.CodigoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)");

                    b.Property<DateTime>("DataExpiracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataGeracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Usado")
                        .HasColumnType("boolean");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Codigos", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.Coleta.ColetaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CloroResidual")
                        .HasColumnType("real");

                    b.Property<float>("ColiformesTotais")
                        .HasColumnType("real");

                    b.Property<int>("CorpoHidricoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EscherichiaColi")
                        .HasColumnType("boolean");

                    b.Property<float>("Floretos")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("OxigenioDissolvido")
                        .HasColumnType("real");

                    b.Property<float>("Ph")
                        .HasColumnType("real");

                    b.Property<float>("Turbidez")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CorpoHidricoId");

                    b.ToTable("Coletas", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("EhPrivado")
                        .HasColumnType("boolean")
                        .HasColumnName("EhPrivado");

                    b.Property<string>("Localizacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Tamanho")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("CorposHidricos", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.Imagem.ImagemEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("ColetaId")
                        .HasColumnType("integer");

                    b.Property<int>("CorpoHidricoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("QualidadeFuturaEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.HasIndex("CorpoHidricoId");

                    b.HasIndex("QualidadeFuturaEntityId");

                    b.ToTable("Imagens", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.MetalPesado.MetalPesadoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColetaId")
                        .HasColumnType("integer");

                    b.Property<float>("Concentracao")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("QualidadeFuturaEntityId")
                        .HasColumnType("integer");

                    b.Property<string>("Unidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ColetaId");

                    b.HasIndex("QualidadeFuturaEntityId");

                    b.ToTable("MetaisPesados", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.Qualidade.QualidadeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CorpoHidricoId")
                        .HasColumnType("integer");

                    b.Property<int>("IQA")
                        .HasColumnType("integer");

                    b.Property<int>("QualidadeFuturaId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CorpoHidricoId");

                    b.HasIndex("QualidadeFuturaId");

                    b.ToTable("Qualidades", "waterPath");
                });

            modelBuilder.Entity("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("CloroResidual")
                        .HasColumnType("real");

                    b.Property<float>("ColiformesTotais")
                        .HasColumnType("real");

                    b.Property<int>("CorpoHidricoId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Data")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EscherichiaColi")
                        .HasColumnType("boolean");

                    b.Property<float>("Floretos")
                        .HasColumnType("real");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<float>("OxigenioDissolvido")
                        .HasColumnType("real");

                    b.Property<float>("Ph")
                        .HasColumnType("real");

                    b.Property<float>("Turbidez")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CorpoHidricoId");

                    b.ToTable("QualidadesFuturas", "waterPath");
                });

            modelBuilder.Entity("QualidadeCianoBacterias", b =>
                {
                    b.HasOne("back_end.src.Domain.CianoBacteria.CianoBacteriaEntity", null)
                        .WithMany()
                        .HasForeignKey("CianoBacteriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.Qualidade.QualidadeEntity", null)
                        .WithMany()
                        .HasForeignKey("QualidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("QualidadeMetaisPesados", b =>
                {
                    b.HasOne("back_end.src.Domain.MetalPesado.MetalPesadoEntity", null)
                        .WithMany()
                        .HasForeignKey("MetalPesadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.Qualidade.QualidadeEntity", null)
                        .WithMany()
                        .HasForeignKey("QualidadeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("UsuarioCorpoHidrico", b =>
                {
                    b.HasOne("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", null)
                        .WithMany()
                        .HasForeignKey("CorpoHidricoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.User.UserEntity", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("back_end.src.Domain.CianoBacteria.CianoBacteriaEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.Coleta.ColetaEntity", "Coleta")
                        .WithMany("CianoBacterias")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", null)
                        .WithMany("CianoBacterias")
                        .HasForeignKey("QualidadeFuturaEntityId");

                    b.Navigation("Coleta");
                });

            modelBuilder.Entity("back_end.src.Domain.Codigo.CodigoEntity", b =>
                {
                    b.HasOne("Domain.User.UserEntity", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("back_end.src.Domain.Coleta.ColetaEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", "CorpoHidrico")
                        .WithMany("Coletas")
                        .HasForeignKey("CorpoHidricoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorpoHidrico");
                });

            modelBuilder.Entity("back_end.src.Domain.Imagem.ImagemEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.Coleta.ColetaEntity", "Coleta")
                        .WithMany("Imagens")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", "CorpoHidrico")
                        .WithMany("Imagens")
                        .HasForeignKey("CorpoHidricoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", null)
                        .WithMany("Imagens")
                        .HasForeignKey("QualidadeFuturaEntityId");

                    b.Navigation("Coleta");

                    b.Navigation("CorpoHidrico");
                });

            modelBuilder.Entity("back_end.src.Domain.MetalPesado.MetalPesadoEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.Coleta.ColetaEntity", "Coleta")
                        .WithMany("MetaisPesados")
                        .HasForeignKey("ColetaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", null)
                        .WithMany("MetaisPesados")
                        .HasForeignKey("QualidadeFuturaEntityId");

                    b.Navigation("Coleta");
                });

            modelBuilder.Entity("back_end.src.Domain.Qualidade.QualidadeEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", "CorpoHidrico")
                        .WithMany()
                        .HasForeignKey("CorpoHidricoId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", "QualidadeFutura")
                        .WithMany("Qualidade")
                        .HasForeignKey("QualidadeFuturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorpoHidrico");

                    b.Navigation("QualidadeFutura");
                });

            modelBuilder.Entity("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", b =>
                {
                    b.HasOne("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", "CorpoHidrico")
                        .WithMany()
                        .HasForeignKey("CorpoHidricoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CorpoHidrico");
                });

            modelBuilder.Entity("back_end.src.Domain.Coleta.ColetaEntity", b =>
                {
                    b.Navigation("CianoBacterias");

                    b.Navigation("Imagens");

                    b.Navigation("MetaisPesados");
                });

            modelBuilder.Entity("back_end.src.Domain.CorpoHidrico.CorpoHidricoEntity", b =>
                {
                    b.Navigation("Coletas");

                    b.Navigation("Imagens");
                });

            modelBuilder.Entity("back_end.src.Domain.QualidadeFutura.QualidadeFuturaEntity", b =>
                {
                    b.Navigation("CianoBacterias");

                    b.Navigation("Imagens");

                    b.Navigation("MetaisPesados");

                    b.Navigation("Qualidade");
                });
#pragma warning restore 612, 618
        }
    }
}
