-- Executar somente em um banco que já possua waterPath."Coletas".
-- Script aditivo: não altera o esquema existente de Coletas.
BEGIN;
CREATE TABLE "waterPath"."Medicoes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ColetaId" integer NOT NULL,
    "codigoMedicao" integer NOT NULL,
    "valor" double precision NULL,
    "unidade" text NOT NULL,
    "censurado" boolean NOT NULL,
    "limite" double precision NULL,
    CONSTRAINT "FK_Medicoes_Coletas_ColetaId" FOREIGN KEY ("ColetaId")
        REFERENCES "waterPath"."Coletas" ("Id") ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_Medicoes_ColetaId_codigoMedicao"
    ON "waterPath"."Medicoes" ("ColetaId", "codigoMedicao");
COMMIT;
