<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
    <Compile Include="../../api/src/*/Domain/*.cs" />
    <Compile Include="../../api/src/Medicoes/Application/**/*.cs" />
    <Compile Include="../../api/src/Medicoes/Controller/*.cs" />
    <Compile Include="../../api/Infrastructure/Data/Tables/*.cs" />
    <Compile Include="../../api/Infrastructure/Data/WaterPathDbContext.cs" />
    <Compile Remove="WaterPathDbContext.cs" />
    <Compile Include="../../api/src/Coleta/Application/DTOs/*.cs" />
    <Compile Include="../../api/Infrastructure/Repository/MedicoesRepository.cs" />
  </ItemGroup>
</Project>
